### ISSUE TITLE
2018.3安装失败

### ISSUE THREAD

**Issue by mogudada** [huage2580/leeks#1]
![image](https://user-images.githubusercontent.com/34201576/87543872-11144c80-c6d8-11ea-9cd9-2482be168fbc.png)

**Comment by liusk98** [comment]
作者使用的是 2019.3 版本开发的， 我是 2020.1.3 版本 ，把源码down下来修改一下就好了

**Comment by zjxuzhj** [comment]
我也装不了。。也是2019.3
