### ISSUE TITLE
phpstorm 2018-3-6使用v1.5.1版本报错

### ISSUE THREAD

**Issue by OMGZui** [huage2580/leeks#100]
![image](https://user-images.githubusercontent.com/15848127/110730636-bed1fe00-825b-11eb-976e-2cb17681eb08.png)

**Comment by dengerYang** [comment]
#88 和这个的解决一样，添加comment-lang3.jar

**Comment by dengerYang** [comment]
考虑到你对java 的maven不熟悉，你可以 [commons-lang3-3.12.0-bin.zip](https://mirrors.tuna.tsinghua.edu.cn/apache//commons/lang/binaries/commons-lang3-3.12.0-bin.zip) ；或者去 [官网](https://commons.apache.org/proper/commons-lang/download_lang.cgi)下载其他版本

**Comment by dengerYang** [comment]
试试最近刚发的1.9.1版本应该没有问题
