### ISSUE TITLE
2021.03安装不上

### ISSUE THREAD

**Issue by a411500412** [huage2580/leeks#106]
idea版本 
![image](https://user-images.githubusercontent.com/35193629/112576443-4196b380-8e2d-11eb-9d2c-5ee4678cfb61.png)

安装提示
![image](https://user-images.githubusercontent.com/35193629/112576476-5115fc80-8e2d-11eb-845e-d81d0c2c1410.png)

**Comment by kanyways** [comment]
试试这个，我自己在2021.1 版本验证成功。

[leeks-1.9.1.zip](https://github.com/huage2580/leeks/files/6293729/leeks-1.9.1.zip)

**Comment by a411500412** [comment]
好的 , 谢谢可以了
