### ISSUE TITLE
2021.1 RC无法使用

### ISSUE THREAD

**Issue by Mrleaf** [huage2580/leeks#107]
![image](https://user-images.githubusercontent.com/16910764/113805178-9ffb5480-9792-11eb-9b7a-659fc1a8dcb2.png)
![image](https://user-images.githubusercontent.com/16910764/113805209-b30e2480-9792-11eb-9ec9-5c9686d728f9.png)
2021.1 RC无法使用

**Comment by kanyways** [comment]
[leeks-1.8.6.1.zip](https://github.com/huage2580/leeks/files/6275906/leeks-1.8.6.1.zip)

fixed

**Comment by dengerYang** [comment]
由于作者在构建的时候，指定idea版本号最大支持2020.3 所以在此之后无法安装，最近我们都有点小忙，后续去除此限制

**Comment by huage2580** [comment]
v1.9.1 解决

**Comment by shady-xia** [comment]
v1.9.1  在2021.1上还是不支持

**Comment by kanyways** [comment]
> v1.9.1 在2021.1上还是不支持
> 
> 插件 'Leeks' (版本 '1.9.1')与当前版本的 IDE 不兼容，因为它需要内部版本号 201.* 或更老的版本，但当前的内部版本号是 WS-211.6693.108

[leeks-1.9.1.zip](https://github.com/huage2580/leeks/files/6293724/leeks-1.9.1.zip)

2021.1 版本验证通过。
