### ISSUE TITLE
Fixed 2021.1 不能安装的问题

### ISSUE THREAD

**Issue by kanyways** [huage2580/leeks#108]
## 更新作者最新的项目源码打包可以支持2021.1的版本

有需要的人自己去下载，个人2020.1验证成功。

[leeks-1.9.1.zip](https://github.com/huage2580/leeks/files/6294180/leeks-1.9.1.zip)

**Comment by WPF0414** [comment]
Plugin 'Leeks' (version '1.9.1') is not compatible with the current version of the IDE, because it requires build 201.* or older but the current build is IU-211.6693.111

**Comment by huage2580** [comment]
> Plugin 'Leeks' (version '1.9.1') is not compatible with the current version of the IDE, because it requires build 201.* or older but the current build is IU-211.6693.111

去release 191下载leeks-1.9.1_fix.zip
