### ISSUE TITLE
idea 2019.3 安装1.91失败

### ISSUE THREAD

**Issue by wuyingdu** [huage2580/leeks#109]
![image](https://user-images.githubusercontent.com/45226442/114494882-adf81c00-9c4f-11eb-946b-900d7461b65f.png)
![2](https://user-images.githubusercontent.com/45226442/114495041-fca5b600-9c4f-11eb-9f18-24ea4fb449e2.png)

**Comment by huage2580** [comment]
不知道说点什么好，下release啊，你下个源码安装想做啥
