### ISSUE TITLE
2021版IDEA安装不了，请处理一下

### ISSUE THREAD

**Issue by China-Wei** [huage2580/leeks#116]
**请确保你完整仔细的阅读了Readme，对关闭的issue进行了搜索，任何重复bug直接close不予回复**  
**IDEA版本(Help-About里面完整复制出来)**  
```
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: May 29, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3788M
Cores: 12
Non-Bundled Plugins: com.huage2580.leeks (1.9.1), io.zhile.research.ide-eval-resetter (2.1.9), cn.yiiguxing.plugin.translate (3.1)
Kotlin: 211-1.4.32-release-IJ6693.72

版本内容

**插件版本号**  
```
1.9.1
```
**错误日志**
```
如果有，请复制出来
```  
**这里描述你的问题**
```
![image](https://user-images.githubusercontent.com/52816610/116634310-3e439a00-a98e-11eb-940f-19575119362f.png)

```
![image](https://user-images.githubusercontent.com/52816610/116635162-9d0a1300-a990-11eb-89dd-82ffd7959dbc.png)

**Comment by China-Wei** [comment]
> **请确保你完整仔细的阅读了Readme，对关闭的issue进行了搜索，任何重复bug直接close不予回复**
> **IDEA版本(Help-About里面完整复制出来)**
> 
> ```
> IntelliJ IDEA 2021.1 (Ultimate Edition)
> Build #IU-211.6693.111, built on April 6, 2021
> Licensed to IntelliJ IDEA Evaluator
> Expiration date: May 29, 2021
> Runtime version: 11.0.10+9-b1341.35 amd64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 3788M
> Cores: 12
> Non-Bundled Plugins: com.huage2580.leeks (1.9.1), io.zhile.research.ide-eval-resetter (2.1.9), cn.yiiguxing.plugin.translate (3.1)
> Kotlin: 211-1.4.32-release-IJ6693.72
> 
> 版本内容
> 
> **插件版本号**  
> ```
> 
> 1.9.1
> 
> ```
> **错误日志**
> ```
> 
> 如果有，请复制出来
> 
> ```
> **这里描述你的问题**
> ```
> 
> ![image](https://user-images.githubusercontent.com/52816610/116634310-3e439a00-a98e-11eb-940f-19575119362f.png)
> 
> ```
> 
> ```

**Comment by dengerYang** [comment]
你没有安装要求提issue ，你的截图看不出对解决问题毫无帮助，请将日志以文本的形式，完整输出来看看

**Comment by China-Wei** [comment]
请问我这边还需要提供什么帮助解决问题

**Comment by dengerYang** [comment]
> 请问我这边还需要提供什么帮助解决问题

上图小窗口中的错误信息过长看不全；其中前面10行数据，完整的以文本的形式发出来
