### ISSUE TITLE
加密货币的编码解释不清晰

### ISSUE THREAD

**Issue by fanlingzhi1234** [huage2580/leeks#118]
readme里面的加密货币的编码解释不清晰，打开提供的新浪列表只能知道满足哪些币可以看，无法获取到可用的编码。以及新浪接口支持货币较少，建议换成更多更新货币的接口。感谢。

**Comment by huage2580** [comment]
确实有更换接口的打算，但是没找到好用的接口

**Comment by 732275239** [comment]
![image](https://user-images.githubusercontent.com/23718569/122370037-4fbe2100-cf91-11eb-850c-09fef3b4395f.png)

然后 btc_编码

**Comment by wengzhenquan** [comment]
不行了啊，只有比特币的了，其它币都没了

**Comment by huage2580** [comment]
v1.9.5 替换了雅虎的行情接口
