### ISSUE TITLE
idea 2021版本新增插件不成功

### ISSUE THREAD

**Issue by Phionse** [huage2580/leeks#123]
**请确保你完整仔细的阅读了Readme，对关闭的issue进行了搜索，任何重复bug直接close不予回复**  
**IDEA版本(Help-About里面完整复制出来)**  
```
版本内容
```
**插件版本号**  
```
最新版本
```
**错误日志**
```
如果有，请复制出来
```  
**这里描述你的问题**
```
```

**Comment by huage2580** [comment]
leeks-1.x.x.zip 直接在IDEA里面安装，注意：直接选择zip文件安装，不要解压。
