### ISSUE TITLE
leeks-master.zip安装失败

### ISSUE THREAD

**Issue by Jett1993** [huage2580/leeks#125]
下载的zip文件安装的时候提示  fail to load plugin descriptor from file  leeks-master.zip 

IntelliJ IDEA 2020.2.4 (Ultimate Edition)
Build #IU-202.8194.7, built on November 24, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: August 20, 2021
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2933M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Lombook Plugin, com.alibaba.p3c.smartfox, com.karateca.jstoolbox, de.ax.powermode, io.zhile.research.ide-eval-resetter, leetcode-editor, net.vektah.codeglance, org.intellij.gitee, some.awesome, MavenRunHelper, org.jetbrains.plugins.vue, cn.wuzhizhan.plugin.mybatis, cn.yiiguxing.plugin.translate, com.baomidou.plugin.idea.mybatisx, izhangzhihao.rainbow.brackets

**Comment by huage2580** [comment]
我服了😓  
去右边release下载，你是第一个下源码安装的
