### ISSUE TITLE
期望增加【当日盈亏总收益】和【持仓总收益】的统计功能

### ISSUE THREAD

**Issue by webi-sh** [huage2580/leeks#135]
如题

**Comment by webi-sh** [comment]
本来想自己做的，但是捣鼓了一下发现没办法正常导入成idea plugin project，不知道哪儿没弄对，后续我如果搞定了我试着自己做一下

**Comment by hundsun23917** [comment]
可能是jdk版本的原因，把自己的jdk改到11的版本试一下
