### ISSUE TITLE
图标好大，隐蔽模式基金名称为拼音

### ISSUE THREAD

**Issue by caoler** [huage2580/leeks#14]
![WX20200730-114141@2x](https://gitee.com/caoler/oss/raw/master/uPic/WX20200730-114141@2x.png)

**Comment by caoler** [comment]
还有就是：我的图标为什么是IDEA的图标
系统：mac 10.15.5
IDEA版本：2019.3.4

**Comment by huage2580** [comment]
：（  
我没mac，mac下的bug基本不解决，隐蔽模式可以关闭的

**Comment by BillowsVan** [comment]
我的是 win10，开启、关闭  超隐蔽模式，都不行，还是显示这个大图标。
请问怎么才能把这个大图标去掉？

**Comment by huage2580** [comment]
图标在v.1.4.3去掉了
