### ISSUE TITLE
没有正常显示股票信息

### ISSUE THREAD

**Issue by lcq0** [huage2580/leeks#144]
Idea版本信息：
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: Key Promoter X, com.alayouni.ansiHighlight, com.huage2580.leeks, jclasslib, GrepConsole, Lombook Plugin, com.alibaba.p3c.xenoamess, com.fun90.idea.patcher, com.github.wangji92.arthas.plugin, com.intellij.ideolog, cn.wuzhizhan.plugin.mybatis, org.jetbrains.plugins.ruby, com.alibabacloud.intellij.toolkit-intellij, net.ashald.envfile, JProfiler, ru.adelf.idea.dotenv, SequenceDiagram, com.codota.csp.intellij, PlantUML integration, com.baomidou.plugin.idea.mybatisx

插件版本：leeks-1.9.9.zip

Event Log：
2022/2/22
11:44	no protocol: 

11:44	Leeks 更新Stock编码数据.

11:44	Leeks 已停止更新Stock编码数据.

**Comment by yulele166** [comment]
去年好像就没有数据了

**Comment by dengerYang** [comment]
1.确保你填写的信息格式是正确，参考示例。
2.如果1不行，口说无凭难排查，不如把你的填写参数发出来让大家测试下。

**Comment by lcq0** [comment]
![配置](https://user-images.githubusercontent.com/17764526/155102409-704c15f3-39ad-4141-8953-37e44dbe9a55.png)
![IL7 ZH$DXGTP(}N07G _J04](https://user-images.githubusercontent.com/17764526/155102415-9a7e0983-327f-4b67-8a1b-76533211de65.png)
配置和最后的效果如上。

**Comment by dengerYang** [comment]
这个是readme使用文档的部分内容，{股票编码有前缀，示例代码：（sh000001,sh600519,sz000001,hk00700,usAAPL）股票编码前缀小写}，所以你应该知道你的填写的内容怎么修改了吧。

**Comment by yulele166** [comment]
![image](https://user-images.githubusercontent.com/17758197/155130562-7dbe3180-ec3b-4545-ae59-9e144a6cc8f3.png)
我关了这个就可以了

**Comment by Eric-sunset** [comment]
建议看看作者的readme，而不是根据百度CSDN的教程- - - 需要分号分割加深市或上市的前缀，而不是逗号分割，只有编号
