### ISSUE TITLE
感谢大佬，新增扩展功能

### ISSUE THREAD

**Issue by jsbxyyx** [huage2580/leeks#15]
感谢大佬，在大佬的基础上增加了定时提醒。[cut_leeks](https://github.com/jsbxyyx/cut_leeks)

**Comment by huage2580** [comment]
手动点赞 👍

**Comment by jsbxyyx** [comment]
大佬 如何pull request

v1.4

feat: 累计盈亏率

v1.3

feat: stock, fund增加买入价格 例子：sh600519|1732.86

v1.2

fix: 解决没有净值估算的基金报错问题；

feat: 增加自定义设置时间；

v1.1

feat: 涨跌无色模式;

feat: 指定时间提醒模式;

v1.0

fix: 股票，基金代码输入框过多展示不完全问题;

fix: 最后刷新时间格式化问题;

fix: 股票更新时间格式问题;

optimize: 基金名称增加基金代码显示;

**Comment by huage2580** [comment]
先同步当前master，然后修改再提交pull就行，由于我review比较慢，可以一小块提交，太多更改我看不过来的
