### ISSUE TITLE
V1.9.8支持基金和股票成本价，持仓，收益率，收益显示

### ISSUE THREAD

**Issue by zxd19910909** [huage2580/leeks#154]
问下作者V1.9.8
支持基金和股票成本价，持仓，收益率，收益显示 这几个值是怎么填写获取的?

**Comment by Nagisazz** [comment]
在idea的setting中配置的值，写在基金编码后

**Comment by huage2580** [comment]
编码,成本价,持仓份额;  

其他会自动计算.
