### ISSUE TITLE
股票没有出来啊

### ISSUE THREAD

**Issue by fengjinqi** [huage2580/leeks#16]
我是mac的ide 2020.1.2版本，基金出来了，股票没有出来

**Comment by huage2580** [comment]
检查股票编码是否正确，编辑后去点refresh按钮  可以参考我的编码字符串
`sh000001,sh000300,sh601939,sz000001,sh600519,hk00700,usAAPL`

**Comment by huage2580** [comment]
v1.4.3尝试修复了
