### ISSUE TITLE
win10,Idea 2019.2 图标太大了

### ISSUE THREAD

**Issue by BillowsVan** [huage2580/leeks#17]
win10,Idea 2019.2 图标太大了，怎么才能取消图标，或者显示的小一些呢。
超隐蔽模式 开启、关闭，图标都没变化

![微信截图_20200806133118](https://user-images.githubusercontent.com/10822729/89494639-2a954980-d7e9-11ea-949e-8289d98945af.png)

**Comment by huage2580** [comment]
V1.4.3直接去掉图标了，我这里测试是ok
