### ISSUE TITLE
idea2023.3版本之后插件报错，无法使用

### ISSUE THREAD

**Issue by jz1017** [huage2580/leeks#175]
idea2023.3版本之后插件报错，无法使用，后续是不在维护更新了吗？

**Comment by WoChen5770** [comment]
我fork了一份，修复了报错
https://github.com/WoChen5770/leeks/releases

**Comment by jz1017** [comment]
> 我fork了一份，修复了报错 https://github.com/WoChen5770/leeks/releases

star了，感谢
