### ISSUE TITLE
股票出不来

### ISSUE THREAD

**Issue by wanglulei** [huage2580/leeks#19]
sh000001,sh000300,sh601939,sz000001,sh600519,hk00700,usAAPL 股票出不来

**Comment by HallenW** [comment]
最新版leeks + IDEA 2020.1.2版本搜不出股票

**Comment by huage2580** [comment]
v1.4.3尝试修复了，不提供任何信息和报错，没办法跟进

**Comment by HallenW** [comment]
> v1.4.3尝试修复了，不提供任何信息和报错，没办法跟进

更新v1.4.3后股票可以出来了,感谢大佬。
