### ISSUE TITLE
字体有些剃头 

### ISSUE THREAD

**Issue by AceInAndroid** [huage2580/leeks#2]
![image](https://user-images.githubusercontent.com/16446233/87665622-c8bd6300-c799-11ea-9411-31c081a65642.png)

字体有些剃头 ，

版本：
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6

**Comment by huage2580** [comment]
我感觉上，是IDEA行高或者字体问题，我用的win10，暂时没办法改。

**Comment by AceInAndroid** [comment]
> 我感觉上，是IDEA行高或者字体问题，我用的win10，暂时没办法改。

![image](https://user-images.githubusercontent.com/16446233/87740201-31492600-c814-11ea-9824-ae8ed0b53e32.png)

还有个问题 初始化的窗口UI就是这样 都挤在一起

**Comment by huage2580** [comment]
行高的问题，我尝试性修复了下，宽度这个，可能是swing在mac平台问题，不太想给它设置最小宽度，不改了
