### ISSUE TITLE
大佬，可以设置股票刷新时间的功能吗，我修改了源码之后打包，结果不能用....

### ISSUE THREAD

**Issue by Smartcat994** [huage2580/leeks#21]
大佬，可以设置股票刷新时间的功能吗，我修改了源码之后打包，结果不能用....
另外股票多于一定数量的时候，就会出现不出现全部的情况。

**Comment by Guo-zf** [comment]
同意，基金也有相同的问题。当基金的数量超过3支时，就会出现显示不全部的问题，麻烦大佬修改一下呗

**Comment by huage2580** [comment]
设置刷新时间我个人不是很想添加，打包问题的话只能自己调了，能跑起来就没问题的。  
显示不全的话，拉高窗口高度就好了，如果加滚动条，每次刷新都要记住滚动位置。下版本会考虑加吧
