### ISSUE TITLE
提问：添加基金代码，刷新leeks依然不显示数据，是我基金代码不对吗，我使用的是天天基金的代码

### ISSUE THREAD

**Issue by vaewzw** [huage2580/leeks#22]

**Comment by jay70501** [comment]
场内基金要把代码放股票。场外基金才放在基金

**Comment by jay70501** [comment]
股票编码示例：sh600519,sz000001

**Comment by vaewzw** [comment]
002987,320007,001071
我填在基金的，我的就是场外基金

> 股票编码示例：sh600519,sz000001

**Comment by jay70501** [comment]
股票编码示例：**sh**600519,**sz**000001

**Comment by jay70501** [comment]
股票编码示例：### sh600519,### sz000001

**Comment by huage2580** [comment]
天天基金的接口，发现部分QDII的基金不返回数据了。你可以自己看看接口有没有数据返回。` http://fundgz.1234567.com.cn/js/基金编码.js`
