### ISSUE TITLE
IDEA 2020.1.3安装插件失败, 提示不兼容

### ISSUE THREAD

**Issue by yyyyyzc** [huage2580/leeks#3]
![image](https://user-images.githubusercontent.com/32948505/87740204-36a67080-c814-11ea-9f49-c683a6e239ba.png)

**Comment by zhaodongxx** [comment]
2018.03报不兼容

**Comment by EwdAger** [comment]
2020.1同报不兼容

**Comment by huage2580** [comment]
v1.3.1 现在支持到了2017.3-2020-1
