### ISSUE TITLE
数据刷不出来了

### ISSUE THREAD

**Issue by huannan** [huage2580/leeks#33]
数据刷不出来了

**Comment by huage2580** [comment]
请详细描述问题,是基金还是股票，附上编码。IDEA版本,如果有错误日志也请附上。

**Comment by immortalHuang** [comment]
idea版本2020.2无法显示

**Comment by huage2580** [comment]
> idea版本2020.2无法显示股票数据

请详细描述问题,是基金还是股票，附上编码。IDEA版本,如果有错误日志也请附上。

**Comment by immortalHuang** [comment]
> > idea版本2020.2无法显示股票数据
> 
> 请详细描述问题,是基金还是股票，附上编码。IDEA版本,如果有错误日志也请附上。

股票，代码是SH603501,idea版本是2020.2旗舰版

**Comment by dengerYang** [comment]
> > > idea版本2020.2无法显示股票数据
> > 
> > 
> > 请详细描述问题,是基金还是股票，附上编码。IDEA版本,如果有错误日志也请附上。
> 
> 股票，代码是SH603501,idea版本是2020.2旗舰版

SH603501在接口中没有返回数据，应该是sh603501吧，小写前缀

**Comment by huage2580** [comment]
无更多反馈
