### ISSUE TITLE
能不能在超隐蔽模式下隐藏这个版本号啊，

### ISSUE THREAD

**Issue by MichaelJokAr** [huage2580/leeks#34]
![image](https://user-images.githubusercontent.com/8246218/99020112-d7295900-2598-11eb-80fe-95f1d1469ed6.png)
版本号一露，还有啥隐蔽

**Comment by dengerYang** [comment]
现在的界面和其他idea的窗口不是很统一，考虑重新做界面，参考gradle的工具栏，并在工具栏中增加一些按钮，例如开始、停止同步（目前定时线程有点占电脑资源）。这个版本号迁移到设置窗口中
