### ISSUE TITLE
表头和基金名称显示全是拼音

### ISSUE THREAD

**Issue by 15572389021** [huage2580/leeks#39]
![image](https://user-images.githubusercontent.com/39123862/100686678-cb6fcc00-33b9-11eb-8537-de994994ae9d.png)
IDEA版本如下
![image](https://user-images.githubusercontent.com/39123862/100686696-d32f7080-33b9-11eb-8e3a-4459cc4fe5a0.png)

**Comment by Meowu** [comment]
这是 feature ，去设置里关闭超隐蔽模式就显示中文了。

**Comment by huage2580** [comment]
如上，去设置关闭就行。
