### ISSUE TITLE
idea 设置界面中文乱码

### ISSUE THREAD

**Issue by laisen86** [huage2580/leeks#4]
操作系统 ：windows 10 
idea 版本:   2020.1

![image](https://user-images.githubusercontent.com/20357539/87777048-63ca4180-c85b-11ea-8e2d-fd349c4aa411.png)

最好 表头可以设置为英文的，更加隐秘

**Comment by huage2580** [comment]
我猜测这方块是你字体问题，可以尝试换字体。隐蔽点的模式，计划在下版本
