### ISSUE TITLE
刷不出来数据，基金 股票都没有。求解

### ISSUE THREAD

**Issue by boy-good** [huage2580/leeks#43]
IDEA版本：2019.2.4
leeks版本：1.6.2

![image](https://user-images.githubusercontent.com/39320533/102316175-6a96e500-3fb0-11eb-9ffc-a5b00f97f8ca.png)
![image](https://user-images.githubusercontent.com/39320533/102316191-708cc600-3fb0-11eb-99e9-c1a04bc77f9f.png)

**Comment by boy-good** [comment]
时间，15点后。是不是leeks停市后就没有数据?

**Comment by huage2580** [comment]
很明显的股票和基金编码对调了，自己仔细设置。
