### ISSUE TITLE
颜色错乱

### ISSUE THREAD

**Issue by 553531284** [huage2580/leeks#45]
![image](https://user-images.githubusercontent.com/26433083/102951671-5ac75580-4508-11eb-9815-c2644b55c062.png)
版本为2020.3

**Comment by dengerYang** [comment]
因为图中选择的数据被表格选中事件覆盖了颜色，我看图片其它数据颜色又是正常的，所以你能简单又清晰的描述下问题吗？

**Comment by 553531284** [comment]
> 因为图中选择的数据被表格选中事件覆盖了颜色，我看图片其它数据颜色又是正常的，所以你能简单又清晰的描述下问题吗？
例如：
涨跌那一列：
第一行的：-0.03
第四行的：-0.03

**Comment by huage2580** [comment]
v1.6.3修复了，感谢反馈
