### ISSUE TITLE
能不能保存表头的顺序呢？

### ISSUE THREAD

**Issue by zzgit00** [huage2580/leeks#46]
工具非常好用！感谢作者！可以光明正大的摸鱼了~[doge]
但是每次重新打开Idea之前调整的列表顺序又变回初始状态了，要是能保存已设置的表头顺序就非常完美了。

**Comment by huage2580** [comment]
感谢反馈，会加入下版本计划。

**Comment by huage2580** [comment]
虽然有点久远，但是确实支持了这个功能
