### ISSUE TITLE
新版本支持

### ISSUE THREAD

**Issue by OMGZui** [huage2580/leeks#52]
2020.3月版本已经不支持了

**Comment by huage2580** [comment]
我测试过是可以的，附上详细IDEA版本，不支持是指什么表现。

**Comment by OMGZui** [comment]
![image](https://user-images.githubusercontent.com/15848127/103752069-2e512480-5044-11eb-88cb-a65f8a6e64e6.png)

**Comment by OMGZui** [comment]
![image](https://user-images.githubusercontent.com/15848127/103752207-5fc9f000-5044-11eb-965d-86967abfc82d.png)

**Comment by huage2580** [comment]
v1.6.2 适配IDEA 2020.3  
我不是有更新日志吗，你为什么非要装个最老的版本

**Comment by OMGZui** [comment]
我去，难怪，我自己没更新
