### ISSUE TITLE
基金正常显示 股票不显示

### ISSUE THREAD

**Issue by gzldc** [huage2580/leeks#55]
系统：Mac os 11.1
idea版本: 2020.3 arm架构
leeks版本:1.6.3[截图](https://gitee.com/gzldc/images/raw/master/2020-12-04/Snipaste_2021-01-12_13-09-13.png)

**Comment by gzldc** [comment]
https://gitee.com/gzldc/images/raw/master/2020-12-04/Snipaste_2021-01-12_13-09-13.png

**Comment by dengerYang** [comment]
截图里股票编码，不符合README.md文件中的说明：（股票编码建议用雪球看网页找，示例：sh600519,sz000001，基金编码zfb上面有，或者天天基金看,请注意 股票编码大小写)；既：sz000700,sh600559

**Comment by gzldc** [comment]
@dengerYang 感谢您的回复！
