### ISSUE TITLE
看不了QDII的基金，QDII的基金显示昨日走势就可以，不用实时估算

### ISSUE THREAD

**Issue by zhaokuix** [huage2580/leeks#60]
![image](https://user-images.githubusercontent.com/28622252/105324278-2f6a8000-5c06-11eb-860d-da170450f34f.png)

**Comment by huage2580** [comment]
天天基金的接口，之前是有QDII的数据的，后面天天基金移除了，没有找到比天天好用的接口，暂时不会改动这个

**Comment by JamesZBL** [comment]
> 天天基金的接口，之前是有QDII的数据的，后面天天基金移除了，没有找到比天天好用的接口，暂时不会改动这个

QDII 的单独走其他接口呢？现在这种啥也看不到。
@huage2580
