### ISSUE TITLE
显示的是英文

### ISSUE THREAD

**Issue by toolmanlife** [huage2580/leeks#70]
![image](https://user-images.githubusercontent.com/64573434/108453580-b95d4580-72a5-11eb-9d2a-d4cc3658d1c3.png)
如何显示为中文呢。pycharm最新版本，leek1.7.1 不用idea也是支持的吧。

**Comment by huage2580** [comment]
不能看完readme吗  
`隐蔽模式默认开启，开启无着色，并且拼音显示，可以自行关闭。`

**Comment by toolmanlife** [comment]
> 不能看完readme吗
> `隐蔽模式默认开启，开启无着色，并且拼音显示，可以自行关闭。`

看了。唯独这行没看到。爱了爱了作者。加油。还会继续更新吗

**Comment by huage2580** [comment]
处于维护阶段，新feature基本不会添加
