### ISSUE TITLE
toolwindow不显示leeks插件

### ISSUE THREAD

**Issue by proactivefly** [huage2580/leeks#72]
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to JBFamily China
You have a perpetual fallback license for this version
Subscription expired on July 26, 2020
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16

toolwindow中 不显示插件

**Comment by huage2580** [comment]
2019.3以下要使用插件1.5.x以下版本
