### ISSUE TITLE
Settings里面显示有bug，部分文字无法显示

### ISSUE THREAD

**Issue by kehanXue** [huage2580/leeks#76]
# 插件版本

leeks-1.8.1.zip

# IDE版本

CLion 2020.2.4
Build #CL-202.7660.37, built on October 7, 2020
Licensed to XXX
Subscription is active until July 6, 2021
For educational use only.
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-65-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 8179M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0, cidr.max.intellisense.file.length=600000
Non-Bundled Plugins: IdeaVIM, artsiomch.cmake, codes.rudolph.idea.cfg, com.chrisrm.idea.MaterialThemeUI, com.fernandojimenez.mattecarbon.theme, com.jetbrains.plugins.ini4idea, com.mallowigi, com.tang, com.widerwille.afterglow, de.ax.powermode, net.vektah.codeglance, org.editorconfig.editorconfigjetbrains, org.jetbrains.plugins.rest, zielu.gittoolbox, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, Docker, org.toml.lang, some.awesome, idea.plugin.protoeditor, org.asciidoctor.intellij.asciidoc, io.ringle.ij.cmakedocs, org.rust.lang, com.huage2580.leeks
Current Desktop: ubuntu:GNOME

# 显示如下图

部分文字无法显示

![Screenshot from 2021-02-25 11-01-49](https://user-images.githubusercontent.com/48554561/109096663-ed7aaf80-7758-11eb-9987-1ef23121cb59.png)

**Comment by huage2580** [comment]
我猜测是字体问题，可以提供你使用的字体名称吗

**Comment by kehanXue** [comment]
IDE字体是Ubuntu
