### ISSUE TITLE
安装插件报错

### ISSUE THREAD

**Issue by yuchengwei** [huage2580/leeks#84]
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
Licensed to https://zhile.io
Subscription is active until July 8, 2089
JRE: 11.0.2+9-b159.60 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

![image](https://user-images.githubusercontent.com/16008836/109279644-f5b81500-7854-11eb-8638-d210436eccef.png)

**Comment by huage2580** [comment]
过低的插件版本不会再提供bug fix,升级IDEA吧
