### ISSUE TITLE
想问下 IDEA 怎么把 jar 导入进去，导进去不是加的依赖吗。。我导入了 然后 settings 哪里并没有呀 

### ISSUE THREAD

**Issue by EruDev** [huage2580/leeks#9]
https://i.loli.net/2020/07/21/MT1hf2Kqkc6zBxA.png
https://i.loli.net/2020/07/21/zm65wsgLtDBRXCu.png

**Comment by huage2580** [comment]
设置->plguins->install from disk 可以百度怎么装插件
